---
# tasks file for jenkins_master

- name: Refresh subscription manager
  command: subscription-manager refresh

- name: clean yum cache
  command:
    cmd: /bin/yum clean all
    warn: false

- name: Install packages
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - java-11-openjdk-devel
      - wget
      - python3

# - name: install jmespath
#   command: pip3 install jmespath

- name: Add jenkins repository
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import a key for jenkins
  ansible.builtin.rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: Install jenkins
  ansible.builtin.yum:
    name: jenkins
    state: latest

- name: permit open traffic on port 8080/tcp
  ansible.posix.firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled

- name: reloading firewall
  service:
    name: firewalld
    state: restarted

- name: Start and enable jenkins
  service:
    name: jenkins
    state: started
    enabled: yes

- name: "Read jenkins initialAdminPassword"
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_password

- name: "Print the file content to a console"
  debug:
    msg: "{{ jenkins_password.stdout_lines[0] }}"

- name: Install plugins
  jenkins_plugin:
    name: scm-api
    version: "621.vda_a_b_055e58f7"
    url_username: admin
    url_password: "{{ jenkins_password.stdout_lines[0] }}"
    url: http://localhost:8080

- name: Install plugins
  jenkins_plugin:
    name: credentials
    version: "1143.vb_e8b_b_ceee347"
    url_username: admin
    url_password: "{{ jenkins_password.stdout_lines[0] }}"
    url: http://localhost:8080

- name: Install plugins
  jenkins_plugin:
    name: structs
    version: "324.va_f5d6774f3a_d"
    url_username: admin
    url_password: "{{ jenkins_password.stdout_lines[0] }}"
    url: http://localhost:8080

- name: Install plugins
  jenkins_plugin:
    name: cloudbees-folder
    version: "6.714.v79e858ef76a_2"
    url_username: admin
    url_password: "{{ jenkins_password.stdout_lines[0] }}"
    url: http://localhost:8080

- name: Install plugins
  jenkins_plugin:
    name: branch-api
    version: "2.1046.v0ca_37783ecc5"
    url_username: admin
    url_password: "{{ jenkins_password.stdout_lines[0] }}"
    url: http://localhost:8080
