---
# tasks file for jenkins_master

- name: Refresh subscription manager
  command: subscription-manager refresh

- name: clean yum cache
  command:
    cmd: /bin/yum clean all
    warn: false

- name: Install packages
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - java-11-openjdk-devel
      - wget

- name: Add jenkins repository
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import a key for jenkins
  ansible.builtin.rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: Install jenkins
  ansible.builtin.yum:
    name: jenkins
    state: latest

- name: permit open traffic on port 8080/tcp
  ansible.posix.firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled

- name: reloading firewall
  service:
    name: firewalld
    state: restarted

- name: Start and enable jenkins
  service:
    name: jenkins
    state: started
    enabled: yes

- name: "Read jenkins initialAdminPassword"
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_password

- name: "Print the file content to a console"
  debug:
    msg: "{{ jenkins_password.stdout_lines }}"
